/**
 * di-engine.js — the Data Interpretation generator (ADR-074, QuantReflex V2 Phase 2).
 *
 * QuantReflex's moat is a GENERATIVE speed engine. DI fits it perfectly: synthesize a small dataset, render it as a
 * chart/table, and ask a calculation about it. This module is the DI analogue of questions.js's numeric generators —
 * it produces questions in the EXACT same shape the drill engine already consumes, plus one extra field:
 *
 *   { question, answer (NUMERIC), category ('di-bar'|'di-line'|'di-pie'|'di-table'|'di-caselet'),
 *     chart (a spec di-charts.js renders), subtype ('<difficulty>:<template>') }
 *
 * Why this reuses everything (no parallel system):
 *   - It SELF-REGISTERS its generators into questions.js's global `categoryGenerators`, so generateQuestion/
 *     generateQuestions/generateMultiTopic route DI through the SAME pipeline as Quant (dedup, difficulty override,
 *     focus/custom/timed/adaptive modes) with zero engine forks.
 *   - It deliberately does NOT join the random `generators` pool (questions.js:782) — so a blind "mixed" Quant drill
 *     never sprouts a chart mid-numpad. DI is reached only by EXPLICIT category/topic selection (Practice → DI).
 *   - On the server (api/duel.js) this file is never require()'d, so the server's categoryGenerators has no DI keys →
 *     DI can't enter duels yet (the duel prompt schema is text-only; DI-in-duels is a documented later step).
 *   - Answers are ALWAYS numeric (the app's numpad has no letters) and ALWAYS "clean" (integer or one decimal),
 *     generated by retry-until-clean so the existing answer-tolerance grades them fairly.
 *
 * Difficulty genuinely changes the THINKING (not just bigger numbers): easy = one lookup; medium = a 2-step
 * calculation (total / difference / average / share); hard = 3+ steps or interpretation (% change, deviation from
 * average, combined share, projection). Reads `_getDifficulty()` (questions.js global) like the Quant generators do.
 *
 * PURE + dual-exported (window.DIEngine / module.exports) so scripts/di-engine.check.js validates it under node.
 */
(function (root) {
  'use strict';

  /* ── tiny pure helpers ── */
  function _ri(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
  function _pick(a) { return a[Math.floor(Math.random() * a.length)]; }
  function _shuffle(a) { var b = a.slice(); for (var i = b.length - 1; i > 0; i--) { var j = Math.floor(Math.random() * (i + 1)); var t = b[i]; b[i] = b[j]; b[j] = t; } return b; }
  function _pickN(a, n) { return _shuffle(a).slice(0, n); }
  function _sum(a) { var s = 0; for (var i = 0; i < a.length; i++) s += a[i]; return s; }
  function _max(a) { return Math.max.apply(null, a); }
  function _min(a) { return Math.min.apply(null, a); }
  function _idxOf(a, v) { return a.indexOf(v); }
  function _round1(x) { return Math.round(x * 10) / 10; }
  /* "clean" = an integer or a value that terminates at one decimal place — so the student's natural answer is exact. */
  function _isClean(x) { return isFinite(x) && Math.abs(x * 10 - Math.round(x * 10)) < 1e-9; }

  /* Current difficulty: reuse the Quant engine's resolver so DI honors the user's setting + adaptive bias. */
  function _difficulty(explicit) {
    if (explicit) return explicit;
    try { if (typeof _getDifficulty === 'function') return _getDifficulty(); } catch (_) {}
    try { if (typeof window !== 'undefined' && typeof window._getDifficulty === 'function') return window._getDifficulty(); } catch (_) {}
    return 'medium';
  }

  /* ── realistic, exam-flavoured themes (CAT / Banking / SSC DI vocabulary) ── */
  var ENTITY_THEMES = [
    { entity: 'Company', items: ['A', 'B', 'C', 'D', 'E', 'F'], pre: 'Company ', metric: 'Sales', unit: '₹ crore' },
    { entity: 'Branch', items: ['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Pune', 'Jaipur'], pre: '', metric: 'Loans Disbursed', unit: '₹ lakh' },
    { entity: 'Product', items: ['P', 'Q', 'R', 'S', 'T', 'U'], pre: 'Product ', metric: 'Units Sold', unit: "'000 units" },
    { entity: 'School', items: ['Rosewood', 'Hilltop', 'Greenfield', 'Lakeside', 'Oakridge', 'Sunrise'], pre: '', metric: 'Students Enrolled', unit: '' },
    { entity: 'Department', items: ['HR', 'Sales', 'IT', 'Finance', 'Ops', 'Legal'], pre: '', metric: 'Employees', unit: '' },
    { entity: 'City', items: ['Indore', 'Surat', 'Nagpur', 'Kochi', 'Patna', 'Bhopal'], pre: '', metric: 'Tickets Booked', unit: '' }
  ];
  var TIME_THEMES = [
    { metric: 'Revenue', unit: '₹ crore' }, { metric: 'Production', unit: "'000 units" },
    { metric: 'Profit', unit: '₹ lakh' }, { metric: 'Website Visitors', unit: "'000" },
    { metric: 'Exports', unit: '₹ crore' }
  ];

  /* n "nice" values (multiples of `step`) in [min,max] — keeps every downstream total/average/share clean-friendly. */
  function _niceValues(n, min, max, step) {
    var lo = Math.ceil(min / step), hi = Math.floor(max / step), out = [];
    for (var i = 0; i < n; i++) out.push(_ri(lo, hi) * step);
    return out;
  }

  /* ───────────────────────── ENTITY datasets (bar / pie / table) ───────────────────────── */
  function _entityDataset() {
    var th = _pick(ENTITY_THEMES);
    var n = _ri(4, 5);
    var items = _pickN(th.items, n).map(function (x) { return th.pre + x; });
    var values = _niceValues(n, 30, 250, 10);
    return { theme: th, labels: items, values: values, unit: th.unit, metric: th.metric, entity: th.entity };
  }

  /* ───────────────────────── TIME dataset (line) ───────────────────────── */
  function _timeDataset() {
    var tm = _pick(TIME_THEMES);
    var start = _pick([2017, 2018, 2019, 2020]);
    var n = _ri(5, 6);
    var labels = []; for (var i = 0; i < n; i++) labels.push(String(start + i));
    var values = _niceValues(n, 40, 220, 10);
    var subject = _pick(['Company XYZ', 'the firm', 'the plant', 'the portal', 'the brand']);
    return { theme: tm, labels: labels, values: values, unit: tm.unit, metric: tm.metric, subject: subject };
  }

  function _unitSuffix(u) { return u ? (' ' + u) : ''; }
  function _metricUnit(d) { return d.metric + (d.unit ? ' (in ' + d.unit + ')' : ''); }

  /* ── ENTITY question templates, keyed by difficulty. Each returns {q, a} or null (retry) ── */
  function _entityQuestion(d, diff) {
    var L = d.labels, V = d.values, total = _sum(V);
    var i = _ri(0, L.length - 1);
    if (diff === 'easy') {
      var t = _pick(['read', 'highest', 'lowest']);
      if (t === 'read') return { q: 'What is the ' + d.metric + ' of ' + L[i] + '?', a: V[i], k: 'read' };
      if (t === 'highest') { var mx = _max(V); return { q: 'Which ' + d.entity + ' has the highest ' + d.metric + '? Enter that value.', a: mx, k: 'max' }; }
      var mn = _min(V); return { q: 'Which ' + d.entity + ' has the lowest ' + d.metric + '? Enter that value.', a: mn, k: 'min' };
    }
    if (diff === 'medium') {
      var t2 = _pick(['total', 'diff', 'avg', 'share']);
      if (t2 === 'total') return { q: 'What is the total ' + d.metric + ' of all ' + L.length + ' ' + d.entity.toLowerCase() + 's shown?', a: total, k: 'total' };
      if (t2 === 'diff') { var j = (i + 1 + _ri(0, L.length - 2)) % L.length; var dv = Math.abs(V[i] - V[j]); if (dv === 0) return null; return { q: 'What is the difference between the ' + d.metric + ' of ' + L[i] + ' and ' + L[j] + '?', a: dv, k: 'diff' }; }
      if (t2 === 'avg') { var av = total / L.length; if (!_isClean(av)) return null; return { q: 'What is the average ' + d.metric + ' across all ' + L.length + ' ' + d.entity.toLowerCase() + 's?', a: _round1(av), k: 'avg' }; }
      var sh = V[i] / total * 100; if (!_isClean(sh)) return null; return { q: L[i] + ' accounts for what percent of the total ' + d.metric + '? (1 decimal)', a: _round1(sh), k: 'share' };
    }
    /* hard */
    var t3 = _pick(['deviation', 'combinedShare', 'project', 'pctMore']);
    if (t3 === 'deviation') { var avg = total / L.length; if (!_isClean(avg)) return null; var dev = (V[i] - avg) / avg * 100; if (!_isClean(dev) || dev === 0) return null; return { q: "By what percent does " + L[i] + "'s " + d.metric + ' differ from the average of all ' + L.length + '? (1 decimal, ignore sign)', a: _round1(Math.abs(dev)), k: 'deviation' }; }
    if (t3 === 'combinedShare') { var j2 = (i + 1) % L.length; var cs = (V[i] + V[j2]) / total * 100; if (!_isClean(cs)) return null; return { q: 'Together, ' + L[i] + ' and ' + L[j2] + ' make up what percent of the total ' + d.metric + '? (1 decimal)', a: _round1(cs), k: 'combinedShare' }; }
    if (t3 === 'project') { var p = _pick([10, 20, 25, 50]); var np = V[i] * (1 + p / 100); if (!_isClean(np)) return null; return { q: 'If ' + L[i] + "'s " + d.metric + ' rises by ' + p + '%, what will its new value be?', a: _round1(np), k: 'project' }; }
    var j3 = (i + 1) % L.length; if (V[j3] === 0) return null; var pm = (V[i] - V[j3]) / V[j3] * 100; if (!_isClean(pm) || pm === 0) return null; return { q: L[i] + "'s " + d.metric + ' is what percent more or less than that of ' + L[j3] + '? (1 decimal, ignore sign)', a: _round1(Math.abs(pm)), k: 'pctMore' };
  }

  /* ── TIME (line) question templates ── */
  function _timeQuestion(d, diff) {
    var L = d.labels, V = d.values, total = _sum(V);
    var i = _ri(0, L.length - 1);
    if (diff === 'easy') {
      var t = _pick(['read', 'peak']);
      if (t === 'read') return { q: 'What was the ' + d.metric + ' in ' + L[i] + '?', a: V[i], k: 'read' };
      return { q: 'What was the highest ' + d.metric + ' recorded in any single year? Enter that value.', a: _max(V), k: 'peak' };
    }
    if (diff === 'medium') {
      var t2 = _pick(['total', 'diff', 'avg']);
      if (t2 === 'total') return { q: 'What is the total ' + d.metric + ' over all ' + L.length + ' years?', a: total, k: 'total' };
      if (t2 === 'diff') { var k = (i + 1) % L.length; return { q: 'What is the difference in ' + d.metric + ' between ' + L[i] + ' and ' + L[k] + '?', a: Math.abs(V[i] - V[k]), k: 'diff' }; }
      var av = total / L.length; if (!_isClean(av)) return null; return { q: 'What is the average annual ' + d.metric + ' over the ' + L.length + ' years?', a: _round1(av), k: 'avg' };
    }
    /* hard: year-on-year % change + biggest jump */
    var t3 = _pick(['yoy', 'biggestJump', 'cumulativeShare']);
    if (t3 === 'yoy') { var y = _ri(1, L.length - 1); if (V[y - 1] === 0) return null; var ch = (V[y] - V[y - 1]) / V[y - 1] * 100; if (!_isClean(ch)) return null; return { q: 'What was the percent change in ' + d.metric + ' from ' + L[y - 1] + ' to ' + L[y] + '? (1 decimal, ignore sign)', a: _round1(Math.abs(ch)), k: 'yoy' }; }
    if (t3 === 'biggestJump') { var best = 0, bi = 1; for (var z = 1; z < V.length; z++) { if (Math.abs(V[z] - V[z - 1]) > best) { best = Math.abs(V[z] - V[z - 1]); bi = z; } } return { q: 'Between which two consecutive years did ' + d.metric + ' change the most? Enter the size of that change.', a: best, k: 'biggestJump' }; }
    var half = Math.floor(L.length / 2); var firstHalf = _sum(V.slice(0, half)); var cs = firstHalf / total * 100; if (!_isClean(cs)) return null; return { q: 'The first ' + half + ' years contributed what percent of the total ' + d.metric + '? (1 decimal)', a: _round1(cs), k: 'cumulativeShare' };
  }

  /* ── CASELET: a worded two-group dataset (Banking favourite). Self-contained text — no chart. ── */
  function _caselet(diff) {
    var ctx = _pick([
      { whole: 'people surveyed', g1: 'men', g2: 'women', act: 'preferred online shopping' },
      { whole: 'students in a class', g1: 'boys', g2: 'girls', act: 'passed the exam' },
      { whole: 'employees in a firm', g1: 'managers', g2: 'staff', act: 'opted for the new policy' },
      { whole: 'visitors to a fair', g1: 'adults', g2: 'children', act: 'bought a ticket online' }
    ]);
    var totalPeople = _ri(4, 12) * 100;            /* round total */
    var g1 = Math.round(totalPeople * _pick([0.4, 0.45, 0.5, 0.55, 0.6]));
    var g2 = totalPeople - g1;
    var p1 = _pick([20, 25, 40, 50, 60, 75]);      /* % of g1 doing the act */
    var p2 = _pick([20, 25, 40, 50, 60, 75]);      /* % of g2 doing the act */
    var a1 = g1 * p1 / 100, a2 = g2 * p2 / 100;
    if (!_isClean(a1) || !_isClean(a2)) return null;
    var stem = 'Out of ' + totalPeople + ' ' + ctx.whole + ', ' + g1 + ' are ' + ctx.g1 + ' and the rest are ' + ctx.g2 + '. '
      + p1 + '% of the ' + ctx.g1 + ' and ' + p2 + '% of the ' + ctx.g2 + ' ' + ctx.act + '. ';
    if (diff === 'easy') return { q: stem + 'How many ' + ctx.g1 + ' ' + ctx.act + '?', a: a1, k: 'caseRead' };
    if (diff === 'medium') return { q: stem + 'In total, how many people ' + ctx.act + '?', a: a1 + a2, k: 'caseTotal' };
    var tot = a1 + a2; if (tot === 0) return null; var sh = a1 / tot * 100; if (!_isClean(sh)) return null;
    return { q: stem + 'Of all the people who ' + ctx.act + ', what percent are ' + ctx.g1 + '? (1 decimal)', a: _round1(sh), k: 'caseShare' };
  }

  /* ── chart spec builders (consumed by di-charts.js) ── */
  function _barChart(d) { return { kind: 'bar', title: _metricUnit(d) + ' by ' + d.entity, unit: d.unit, yLabel: d.metric, labels: d.labels.slice(), values: d.values.slice() }; }
  function _pieChart(d) { return { kind: 'pie', title: 'Share of ' + _metricUnit(d), unit: d.unit, labels: d.labels.slice(), values: d.values.slice() }; }
  function _lineChart(d) { return { kind: 'line', title: _metricUnit(d) + ' of ' + d.subject + ' over the years', unit: d.unit, xLabel: 'Year', yLabel: d.metric, labels: d.labels.slice(), values: d.values.slice() }; }
  function _tableChart(d) { return { kind: 'table', title: _metricUnit(d) + ' by ' + d.entity, columns: [d.entity, d.metric + (d.unit ? ' (' + d.unit + ')' : '')], rows: d.labels.map(function (l, i) { return [l, String(d.values[i])]; }) }; }

  /* ── the per-category generators. Each: build dataset → build a clean question (retry) → attach chart. ── */
  function _genEntity(category, chartFn, diff) {
    var noun = category === 'di-table' ? 'table' : 'chart';
    for (var attempt = 0; attempt < 40; attempt++) {
      var d = _entityDataset();
      var qa = _entityQuestion(d, diff);
      if (!qa) continue;
      return { question: 'Study the ' + noun + ' and answer: ' + qa.q, answer: qa.a, category: category, chart: chartFn(d), subtype: diff + ':' + qa.k };
    }
    /* guaranteed-clean fallback: a direct read is always an integer */
    var d2 = _entityDataset(), i = _ri(0, d2.labels.length - 1);
    return { question: 'Study the ' + noun + ' and answer: What is the ' + d2.metric + ' of ' + d2.labels[i] + '?', answer: d2.values[i], category: category, chart: chartFn(d2), subtype: diff + ':read' };
  }
  function _genLine(diff) {
    for (var attempt = 0; attempt < 40; attempt++) {
      var d = _timeDataset();
      var qa = _timeQuestion(d, diff);
      if (!qa) continue;
      return { question: 'Study the graph and answer: ' + qa.q, answer: qa.a, category: 'di-line', chart: _lineChart(d), subtype: diff + ':' + qa.k };
    }
    var d2 = _timeDataset(), i = _ri(0, d2.labels.length - 1);
    return { question: 'Study the graph and answer: What was the ' + d2.metric + ' in ' + d2.labels[i] + '?', answer: d2.values[i], category: 'di-line', chart: _lineChart(d2), subtype: diff + ':read' };
  }
  function _genCaselet(diff) {
    for (var attempt = 0; attempt < 40; attempt++) {
      var qa = _caselet(diff);
      if (qa) return { question: qa.q, answer: qa.a, category: 'di-caselet', subtype: diff + ':' + qa.k };
    }
    var qa2 = _caselet('easy') || { q: 'Out of 400 people surveyed, 240 are men. How many are men?', a: 240, k: 'caseRead' };
    return { question: qa2.q, answer: qa2.a, category: 'di-caselet', subtype: diff + ':' + qa2.k };
  }

  /* Public: generate ONE DI question for a category (difficulty optional → reads the user's setting). */
  function generate(category, difficulty) {
    var diff = _difficulty(difficulty);
    if (diff !== 'easy' && diff !== 'medium' && diff !== 'hard') diff = 'medium';
    switch (category) {
      case 'di-bar': return _genEntity('di-bar', _barChart, diff);
      case 'di-pie': return _genEntity('di-pie', _pieChart, diff);
      case 'di-table': return _genEntity('di-table', _tableChart, diff);
      case 'di-line': return _genLine(diff);
      case 'di-caselet': return _genCaselet(diff);
      default: return _genEntity('di-bar', _barChart, diff);
    }
  }

  /* category id → human label (the DI subject's drill categories). */
  var CATEGORY_LABELS = {
    'di-table': 'Data Tables', 'di-bar': 'Bar Graphs', 'di-line': 'Line Graphs',
    'di-pie': 'Pie Charts', 'di-caselet': 'Caselets'
  };

  /* No-arg generators (the shape questions.js's categoryGenerators map expects: called as gen()). */
  var generators = {};
  Object.keys(CATEGORY_LABELS).forEach(function (cat) { generators[cat] = function () { return generate(cat); }; });

  /* Register DI into questions.js's dispatch map so Practice/Stats reuse the SAME pipeline. Idempotent. The random
     `generators` POOL (questions.js:782) is intentionally NOT touched, so blind Quant mixes never pull a chart. */
  function registerInto(map) { if (!map) return; Object.keys(generators).forEach(function (k) { map[k] = generators[k]; }); }
  try { if (typeof categoryGenerators !== 'undefined' && categoryGenerators) registerInto(categoryGenerators); } catch (_) {}

  var DIEngine = {
    CATEGORY_LABELS: CATEGORY_LABELS,
    categories: function () { return Object.keys(CATEGORY_LABELS); },
    label: function (c) { return CATEGORY_LABELS[c] || c; },
    generate: generate,
    generators: generators,
    registerInto: registerInto
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = DIEngine;
  if (typeof window !== 'undefined') window.DIEngine = DIEngine;
  else root.DIEngine = DIEngine;
})(this);
